#!/usr/bin/python3 -u

import glob
import imp
import os
import sys
import subprocess


data = sys.stdin.readlines()

if (os.path.isdir('hooks/post-receive.d')):
    for hook in os.listdir('hooks/post-receive.d'):
        hook = os.path.join('hooks/post-receive.d', hook)
        if (hook.endswith(('~','.bak','.rpmsave','.rpmnew')) or
                not (os.path.isfile(hook) and os.access(hook, os.X_OK))):
            continue
        hook_process = subprocess.Popen([hook], stdin=subprocess.PIPE)
        try:
            for line in data:
                hook_process.stdin.write(line.encode('utf-8'))
            hook_process.communicate()
        except BrokenPipeError:
            pass
        except Exception as e:
            print('Error in hook ', hook)
            print(e)

for pluginfile in glob.glob('hooks/post-receive.python.d/*.py'):
    try:
        plugin = imp.load_source(os.path.basename(pluginfile), pluginfile)
        plugin.run(data)
    except Exception as e:
        print('Error in hook ', pluginfile)
        print(e)
